name: tpad-text-editor # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '6.5.1.4-3gna1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple text editor
description: |
   A simple, easy to use, fast text editor.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
